# Generated by Django 3.2.9 on 2021-11-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200709_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_models',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
