# Generated by Django 3.0.7 on 2020-07-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_field',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('capacity', models.FloatField(null=True)),
                ('farm_name', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('no_turbines', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wind_farm',
            fields=[
                ('capacity', models.FloatField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('noofturbines', models.IntegerField()),
            ],
        ),
    ]
